In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('car_data.csv')
df.drop(columns=['Car_Name'] , inplace=True)

In [14]:
# df = pd.get_dummies(df , columns=['Fuel_Type'] , drop_first=True)
# df= pd.get_dummies(df , columns = ['Transmission'] , drop_first=True)
df= pd.get_dummies(df , columns = ['Seller_Type'] , drop_first=True)

df

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual,Seller_Type_Individual
0,2014,3.35,5.59,27000,0,False,True,True,False
1,2013,4.75,9.54,43000,0,True,False,True,False
2,2017,7.25,9.85,6900,0,False,True,True,False
3,2011,2.85,4.15,5200,0,False,True,True,False
4,2014,4.60,6.87,42450,0,True,False,True,False
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,True,False,True,False
297,2015,4.00,5.90,60000,0,False,True,True,False
298,2009,3.35,11.00,87934,0,False,True,True,False
299,2017,11.50,12.50,9000,0,True,False,True,False
300,2016,5.30,5.90,5464,0,False,True,True,False

In [17]:
import numpy as np

df = pd.DataFrame({
    'Marks' : [40,35,65,31,70,95,18]
})

df['Result'] = np.where(df['Marks'] > 40 , 'Pass' , 'Fail')
df['Grade'] = np.where(df['Marks'] > 75 , 'a' , np.where(df['Marks'] > 50 , 'b' , 'c'))

df

   Marks Result Grade
0     40   Fail     c
1     35   Fail     c
2     65   Pass     b
3     31   Fail     c
4     70   Pass     b
5     95   Pass     a
6     18   Fail     c

In [21]:
# arithmatic_operation

df = pd.DataFrame({
    'math' : [45,60,75],
    'sci' : [50,60,70]
})

In [22]:


df['total'] = df['math'] + df['sci']
df['average'] = df['total']/2
df

   math  sci  total  average
0    45   50     95     47.5
1    60   60    120     60.0
2    75   70    145     72.5

In [23]:
# test,train,split

In [61]:
df = pd.read_csv('car_data.csv')
df.drop(columns=['Car_Name'] , inplace=True)
df = pd.get_dummies(df,drop_first=True)

y = df['Selling_Price']
print(y)

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [62]:
x = df.drop(columns=['Selling_Price'])
x

,Year,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,5.59,27000,0,False,True,False,True
1,2013,9.54,43000,0,True,False,False,True
2,2017,9.85,6900,0,False,True,False,True
3,2011,4.15,5200,0,False,True,False,True
4,2014,6.87,42450,0,True,False,False,True
...,...,...,...,...,...,...,...,...
296,2016,11.60,33988,0,True,False,False,True
297,2015,5.90,60000,0,False,True,False,True
298,2009,11.00,87934,0,False,True,False,True
299,2017,12.50,9000,0,True,False,False,True
300,2016,5.90,5464,0,False,True,False,True

In [63]:
print('x:' , x.shape)
print('y:' , y.shape)

x: (301, 8)
y: (301,)

In [64]:
x

,Year,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,5.59,27000,0,False,True,False,True
1,2013,9.54,43000,0,True,False,False,True
2,2017,9.85,6900,0,False,True,False,True
3,2011,4.15,5200,0,False,True,False,True
4,2014,6.87,42450,0,True,False,False,True
...,...,...,...,...,...,...,...,...
296,2016,11.60,33988,0,True,False,False,True
297,2015,5.90,60000,0,False,True,False,True
298,2009,11.00,87934,0,False,True,False,True
299,2017,12.50,9000,0,True,False,False,True
300,2016,5.90,5464,0,False,True,False,True

In [65]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [67]:
print('x_test:', x_test.shape)
print('x_train:', x_train.shape)

print('y_test:', y_test.shape)
print('y_train:', y_train.shape)

print(y_test)

x_test: (61, 8)
x_train: (240, 8)
y_test: (61,)
y_train: (240,)
177     0.35
289    10.11
228     4.95
198     0.15
60      6.95
       ...
234     5.50
296     9.50
281     2.10
285     7.40
182     0.30
Name: Selling_Price, Length: 61, dtype: float64